version: 3
jobs:
  lint:
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Install Rust Components
          command: rustup component add rustfmt clippy
      - run:
          name: Component Version Information
          command: cargo fmt -- --version; cargo clippy -- --version
      - run:
          name: Setup Env
          command: |
            echo 'export RUSTFLAGS="-D warnings"' >> $BASH_ENV
      - run:
          name: Lint (rustfmt)
          command: |
            cargo fmt -- --check
      - run:
          name: Lint (clippy)
          command: |
            cargo clippy --all-features
  build:
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run:
          name: Setup Additional Languages
          command: |
            echo "deb http://http.us.debian.org/debian/ buster-backports main" | sudo tee -a /etc/apt/sources.list
            echo "deb-src http://http.us.debian.org/debian/ buster-backports main" | sudo tee -a /etc/apt/sources.list
            sudo apt-get update
            sudo apt-get install -y apt-transport-https python3-all-dev python3-pip clang llvm default-jdk golang-1.14-go/buster-backports
            echo 'export PATH=$PATH:/usr/lib/go-1.14/bin' >> $BASH_ENV
            python3 -m pip install pyre-check==0.0.59
            python3 -m pip install numpy==1.20.1
            wget https://packages.microsoft.com/config/debian/10/packages-microsoft-prod.deb -O packages-microsoft-prod.deb
            sudo dpkg -i packages-microsoft-prod.deb
            sudo apt-get update
            sudo apt-get install -y dotnet-sdk-2.1 dotnet-sdk-3.1
            curl -fsSL https://deno.land/x/install/install.sh | sh
            echo 'export DENO_INSTALL="/home/circleci/.deno"' >> $BASH_ENV
            echo 'export PATH="$DENO_INSTALL/bin:$PATH"' >> $BASH_ENV
      - run:
          name: Version Information
          command: |
            rustc --version
            cargo --version
            rustup --version
            python3 --version
            clang++ --version
            javac -version
            go version
            dotnet --list-sdks
            deno --version
      - run:
          name: Setup Env
          command: |
            echo 'export RUSTFLAGS="-D warnings"' >> $BASH_ENV
      - run:
          name: Build and Test
          # Build all targets to ensure examples are built as well.
          command: |
            cargo build --all-targets
            cargo test
            cargo build --release --all-targets --all-features
            cargo test --release --all-features

  # docs-build and docs-deploy are adapted from
  # https://circleci.com/blog/deploying-documentation-to-github-pages-with-continuous-integration/.
  docs-build:
    docker:
      - image: circleci/rust:buster
    steps:
      - checkout
      - run:
          name: Version Information
          command: rustc --version; cargo --version; rustup --version
      - run:
          name: Generate documentation
          command: |
            cargo doc --all-features
      - persist_to_workspace:
          root: target
          paths: doc

  docs-deploy:
    docker:
      - image: node:8.10.0
    steps:
      - checkout
      - attach_workspace:
          at: target
      - run:
          name: Disable jekyll builds
          command: touch target/doc/.nojekyll
      - run:
          name: Install and configure gh-pages
          command: |
            npm install -g --silent gh-pages@2.0.1
            git config user.email "ci-build@calibra.com"
            git config user.name "ci-build"
      - add_ssh_keys:
          fingerprints:
            - "f9:01:7b:01:d0:ea:df:5e:c4:84:38:b7:92:93:e5:c8"
      - run:
          name: Deploy to gh-pages branch
          command: |
            gh-pages --dotfiles --message "[skip ci] documentation update" --dist target/doc

workflows:
  version: 2
  build:
    jobs:
      - lint
      - build
      - docs-build
      - docs-deploy:
          requires:
            - lint
            - build
            - docs-build
          filters:
            branches:
              only: master
