// Copyright (c) Facebook, Inc. and its affiliates.

#if !canImport(ObjectiveC)
    import XCTest

    extension SerdeTests {
        // DO NOT MODIFY: This is autogenerated, use:
        //   `swift test --generate-linuxmain`
        // to regenerate.
        static let __allTests__SerdeTests = [
            ("testCheckThatKeySlicesAreIncreasing", testCheckThatKeySlicesAreIncreasing),
            ("testDeserializer", testDeserializer),
            ("testSerializeI128", testSerializeI128),
            ("testSerializeInt16", testSerializeInt16),
            ("testSerializeInt32", testSerializeInt32),
            ("testSerializeInt64", testSerializeInt64),
            ("testSerializeInt8", testSerializeInt8),
            ("testSerializer", testSerializer),
            ("testSerializeU128", testSerializeU128),
            ("testSerializeUint16", testSerializeUint16),
            ("testSerializeUint32", testSerializeUint32),
            ("testSerializeUint8", testSerializeUint8),
            ("testSortMapEntries", testSortMapEntries),
            ("testULEB128Encoding", testULEB128Encoding),
        ]
    }

    public func __allTests() -> [XCTestCaseEntry] {
        return [
            testCase(SerdeTests.__allTests__SerdeTests),
        ]
    }
#endif
